data:
  # CSV for path and metadata to training examples.
  dataset:
    seed: 123
    max_num_res: 128
    cache_num_res: 0
    min_num_res: 0
    subset: null # take first #subset instances from dataset that are within the desired sequence-length range
    samples_per_eval_length: 5 # #samples (WITH replacement) from each sequence-length to evaluate on
    num_eval_lengths: 8 # number of different sequence lengths to evaluate on
    min_eval_length: 500 # TODO: should be MAX eval length accroding to code logic
    csv_path: ./preprocessed/metadata.csv
  loader:
    num_workers: 4
    prefetch_factor: 10
  sampler: # parameters for batch sampler LengthBatcher
           # actual_batch_size = min(max_batch_size, max_num_res_squared // seq_len^2 + 1)
    max_batch_size: 100
    max_num_res_squared: 500_000

interpolant:
  min_t: 1e-2
  rots:
    train_schedule: linear # TODO: setting to 'exp' will have no effect? rot_sample_kappa not being called 
    sample_schedule: exp 
    exp_rate: 10
  trans:
    train_schedule: linear  # TODO: setting to 'exp' will have no effect? rot_sample_kappa not being called 
    sample_schedule: linear # TODO: setting to 'exp' will have no effect; alternative euler step for translations not implemented -> interpolant._trans_euler_step
  sampling:
    num_timesteps: 100
  self_condition: ${model.edge_features.self_condition}

model:
  node_embed_size: 256
  edge_embed_size: 128
  symmetric: False
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    embed_diffuse_mask: False
    max_num_res: 2000
    timestep_int: 1000
  edge_features:
    single_bias_transition_n: 2
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    relpos_k: 64
    use_rbf: True
    num_rbf: 32
    feat_dim: 64
    num_bins: 22
    self_condition: True # edge reps include distogram of previous-step t1-calpha-location-prediction (applied stochastically, 50% of the time -> FlowModule.trainig_step())
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 128
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 6

experiment:
  debug: False
  seed: 123
  num_devices: 2
  warm_start: null
  warm_start_cfg_override: True
  use_swa: False
  batch_ot:
    enabled: True
    cost: kabsch
    noise_per_sample: 1
    permute: False
  training:
    min_plddt_mask: null
    loss: se3_vf_loss # one of "bb_atom_loss", "trans_loss", "dist_mat_loss", "auxiliary_loss", "rots_vf_loss", "se3_vf_loss"; will output specified+'auxiliary_loss' (FlowModule->training_step())
    bb_atom_scale: 0.1 # convert coordinates from Angstrom to nm
    trans_scale: 0.1 # convert coordinates from Angstrom to nm
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9 # clip loss normaliser 1/(1-t) to [1/(0.1), 1/1]
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0
    aux_loss_t_pass: 0.25 # fraction of trajectory to use auxiliary losses for
  wandb:
    name: baseline
    project: se3-fm
    save_code: True
    tags: []
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    min_epochs: 1 # prevents early stopping
    max_epochs: 200
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    strategy: ddp
    check_val_every_n_epoch: 2
    accumulate_grad_batches: 2
  checkpointer:
    dirpath: ckpt/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: True
    save_top_k: 3
    monitor: valid/non_coil_percent # TODO: we want to monitor AB like-ness
    mode: max
