# TODO: update after changes to base.yaml

# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - _self_

inference:

  # Use this to write with date-time stamp.
  name: run_${now:%Y-%m-%d}_${now:%H-%M}
  seed: 123
  ckpt_path: weights/published.ckpt
  output_dir: inference_outputs/

  use_gpu: True
  num_gpus: 2

  interpolant:
    min_t: 1e-2
    rots:
      corrupt: True
      sample_schedule: exp
      exp_rate: 10
    trans:
      corrupt: True
      sample_schedule: linear
    sampling:
      num_timesteps: 100
    self_condition: True



# TODO: should be moved under data
data: # TODO: not sure if this overrides the base.yaml
# TODO: this configuration is incorrect for the new DatModule/loader
  samples:                          
    samples_per_length: 5   # sample k seqs (WITH replacement) per seq-length to eval on
    num_gen_lengths: 8          # num different seq-lengths to generate at during validation
    max_gen_length: 260         # max seq-length to generate at during validation


    bsampler:
      num_batches_per_epoch_per_gpu: 2000
      num_struc_samples: null
      max_batch_size: 100
      max_num_res_squared: 500_000    # true_batch_size = min(max_batch_size, max_num_res_squared // seq_len^2 + 1)



  samples:

    # Number of backbone samples per sequence length.
    samples_per_length: 10

    # Minimum sequence length to sample.
    min_length: 60

    # Maximum sequence length to sample.
    max_length: 128

    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 1

    # Subset (explicit list) of lengths to sample. If null, sample all targets.
    length_subset: null

    overwrite: False
