defaults:
  - base
  - _self_
  
data:
  module:
    inference_only_mode: True
    loaders:
        num_workers: 1
        prefetch_factor: 10
  inference:
    samples:                                  # config for antibodies to generate
      seed: 123                               # determines random length combos chosen for tot_length
      csv_path: ./ab_processed_newclust/metadata.csv # reference dataset from which to re-construct length-distributions of VH, VL
      min_length: 215                         # hard filters to apply before constructing the reference PMF
      max_length: 260
      min_length_heavy: 109
      max_length_heavy: 145
      min_length_light: 99
      max_length_light: 121
      num_combos: 100                         # number of unique VH/VL-length combinations to sample
      num_samples_per_combo: 2
experiment:
  inference:
    output_dir: chainid_feat_newsample_outputs/
    ckpt_path: ckpt/abfm/reljump50+chainid_aux75p_ft_rbl_newclust_nodataslipts_220ep_bs10_accum6_adaptlr0.2_3/2024-07-09_16-35-51/epoch=208-step=160512.ckpt #ckpt/abfm/reljump50+chainid_aux75p_ft_rbl_newclust_nodataslipts_220ep_bs10_accum6_adaptlr0.2_3/2024-07-09_16-35-51/epoch=32-step=25344.ckpt #weights/published.ckpt 
    name: run_${now:%Y-%m-%d}_${now:%H-%M}
    num_gpus: ${experiment.num_devices}                   # TODO: handle this in code
  wandb:
    name: phoenix1_inference
    project: abfm
    save_code: True
    tags: []