defaults:
  - base
  - _self_
  
data:
  module:
    inference_only_mode: True
    loaders:
        num_workers: 4
        prefetch_factor: 10
  inference:
    samples:                                  # config for antibodies to generate
      seed: 123                               # determines random length combos chosen for tot_length
      min_length: 215
      max_length: 260
      min_length_heavy: 109
      max_length_heavy: 145
      min_length_light: 99
      max_length_light: 121
      samples_per_length: 4
      length_step: 1
      length_list: null                       # explicit list of lengths at which to generate
      overwrite: False
    bsampler:
      seed: 123
      # num_batches_per_epoch_per_gpu: 90     # set close to samples_per_length*num_lengths/num_gpus
      num_struc_samples: null
      max_batch_size: 1                     # TODO: currently sample() only handles batches of size one
      max_num_res_squared: 500_000          # true_batch_size = min(max_batch_size, max_num_res_squared // seq_len^2 + 1)

experiment:
  inference:
    output_dir: inference_outputs/
    ckpt_path: ckpt/abfm/train_debug/2024-04-16_15-43-44/last.ckpt #weights/published.ckpt 
    name: run_${now:%Y-%m-%d}_${now:%H-%M}
    num_gpus: 2
  wandb:
    name: inference_debug
    project: abfm
    save_code: True
    tags: []