defaults:
  - base
  - _self_
  
data:
  module:
    inference_only_mode: True
    loaders:
        num_workers: 1
        prefetch_factor: 10
  inference:
    samples:                                  # config for antibodies to generate
      seed: 123                               # determines random length combos chosen for tot_length
      min_length: 215
      max_length: 260
      min_length_heavy: 109
      max_length_heavy: 145
      min_length_light: 99
      max_length_light: 121
      samples_per_length: 4
      length_step: 1
      length_list: null                       # explicit list of lengths at which to generate
      overwrite: False
experiment:
  inference:
    output_dir: inference_outputs/
    ckpt_path: ckpt/abfm/phoenix1_overfit/2024-05-07_13-21-34/last.ckpt #/vols/opig/users/vavourakis/epoch=3-step=23648.ckpt #weights/published.ckpt 
    name: run_${now:%Y-%m-%d}_${now:%H-%M}
    num_gpus: ${experiment.num_devices}                   # TODO: handle this in code
  wandb:
    name: phoenix1_inference
    project: abfm
    save_code: True
    tags: []